spring.application.name=open-source-project-portal
server.port=8080

# GitHub Repository Configuration
github.owner=kishoreavk7
github.repository=open-source-project-portal

# Actuator Health and Info Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always